### ISSUE TITLE
Destroy event listener

### ISSUE THREAD

**Issue by andredewaard** [cklmercer/vue-events#7]
Events won't be destroyed when used with vue-router and you go to new route.

On Both pages i listen to an event called from a pagination component.
When i start on 1 page and go the the second page the event listener in page 1 will still fire.

**Comment by cklmercer** [comment]
This is somewhat intentional/innate. The event bus itself is global, so when you register your event listener your actually registering it on a unique vm.. not your component.

Two possible solutions off the top of my head..

* You could have your handler perform a check before carrying out it's action.
* You could use the `$off` method to remove the event listener whenever you route to a different component.

Official docs: [vm.$off](https://vuejs.org/v2/api/#vm-off)

**Comment by cklmercer** [comment]
I updated the plugin today to provide a couple aliases for `vm.$off`. You'll need to upgrade to version `3.0.0` to have access to them though.
